// <auto-generated />
using System;
using MangaLibraryAPI.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaLibraryAPI.Migrations
{
    [DbContext(typeof(MangaLibraryContext))]
    [Migration("20231203045218_ShortenDescriptions")]
    partial class ShortenDescriptions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MangaLibraryAPI.Entities.Manga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<byte>("Bookmark")
                        .HasColumnType("tinyint");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<short>("ReleaseYear")
                        .HasColumnType("smallint");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TitleEnglish")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitleJapanese")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Mangas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Bookmark = (byte)1,
                            Poster = "https://cdn.myanimelist.net/images/manga/1/157897.jpg",
                            Rating = 9.84f,
                            ReleaseYear = (short)1989,
                            ShortDescription = "Guts, a former mercenary now known as the \"Black Swordsman\", is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything...",
                            Status = (byte)3,
                            TitleEnglish = "Berserk",
                            TitleJapanese = "ベルセルク"
                        },
                        new
                        {
                            ID = 2,
                            Bookmark = (byte)1,
                            Poster = "https://cdn.myanimelist.net/images/manga/3/265854.jpg",
                            Rating = 9.36f,
                            ReleaseYear = (short)2005,
                            ShortDescription = "\"Akumajō Dracula: Yami no Juin\" had in Japan its own comic series that lasted all of two volumes. The comic series of the same name was created in 2005 by company Mediafactory, and it follows events that overlap with bonus-material comic...",
                            Status = (byte)4,
                            TitleEnglish = "Castlevania: Curse of Darkness",
                            TitleJapanese = "悪魔城ドラキュラ 闇の呪印"
                        },
                        new
                        {
                            ID = 3,
                            Bookmark = (byte)1,
                            Poster = "https://cover.imglib.info/uploads/cover/desu-noto/cover/5UcB013CNhll_250x350.jpg",
                            Rating = 9.6f,
                            ReleaseYear = (short)2003,
                            ShortDescription = "Ryuk, a god of death, drops his Death Note into the human world for personal pleasure. In Japan, prodigious high school student Light Yagami stumbles upon it. Inside the notebook, he finds a chilling message: those whose names are written in it shall die.",
                            Status = (byte)4,
                            TitleEnglish = "Death Note",
                            TitleJapanese = "デスノート"
                        });
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "obichnichelovek@vk.com",
                            Name = "Admin",
                            Password = "SuperSecretPassword",
                            Role = (byte)2
                        });
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.Manga", b =>
                {
                    b.HasOne("MangaLibraryAPI.Entities.User", null)
                        .WithMany("Mangas")
                        .HasForeignKey("UserID");

                    b.OwnsOne("MangaLibraryAPI.Entities.MangaDetails", "Details", b1 =>
                        {
                            b1.Property<int>("MangaID")
                                .HasColumnType("int");

                            b1.Property<string>("Artist")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Author")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<short>("Chapters")
                                .HasColumnType("smallint");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<DateTime>("PublishDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Publishing")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TitleRomaji")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<DateTime>("UpdateDate")
                                .HasColumnType("datetime2");

                            b1.Property<short>("Volumes")
                                .HasColumnType("smallint");

                            b1.Property<int>("Votes")
                                .HasColumnType("int");

                            b1.HasKey("MangaID");

                            b1.ToTable("MangaDetails");

                            b1.WithOwner("Manga")
                                .HasForeignKey("MangaID");

                            b1.Navigation("Manga");

                            b1.HasData(
                                new
                                {
                                    MangaID = 1,
                                    Artist = "Kentaro Miura",
                                    Author = "Kentaro Miura",
                                    Chapters = (short)376,
                                    Description = "Guts, a former mercenary now known as the \"Black Swordsman\", is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings.\n\nSetting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him—and his loved one—of their humanity.",
                                    PublishDate = new DateTime(2023, 12, 3, 8, 52, 18, 412, DateTimeKind.Local).AddTicks(8493),
                                    Publishing = "Hakusensha, Dark Horse Comics, XL Media",
                                    TitleRomaji = "Beruseruku",
                                    UpdateDate = new DateTime(2023, 12, 3, 8, 52, 18, 412, DateTimeKind.Local).AddTicks(8515),
                                    Volumes = (short)41,
                                    Votes = 12646
                                },
                                new
                                {
                                    MangaID = 2,
                                    Artist = "SASAKURA Kou",
                                    Author = "SASAKURA Kou",
                                    Chapters = (short)4,
                                    Description = "\"Akumajō Dracula: Yami no Juin\" had in Japan its own comic series that lasted all of two volumes. The comic series of the same name was created in 2005 by company Mediafactory, and it follows events that overlap with bonus-material comic Prelude of Revenge, whose story was conceived by Ayami Kojima; the series is, according to her, a true extension of the of both Prelude and therein the game's actual story. Adding to its authenticity is the knowledge that Koji Igarashi completely supervised its creation.",
                                    PublishDate = new DateTime(2023, 12, 3, 8, 52, 18, 412, DateTimeKind.Local).AddTicks(8524),
                                    Publishing = "Media Factory",
                                    TitleRomaji = "Akumajō Dracula: Yami no Juin",
                                    UpdateDate = new DateTime(2023, 12, 3, 8, 52, 18, 412, DateTimeKind.Local).AddTicks(8533),
                                    Volumes = (short)2,
                                    Votes = 42
                                },
                                new
                                {
                                    MangaID = 3,
                                    Artist = "Takeshi Obata",
                                    Author = "Tsugumi Ohba",
                                    Chapters = (short)117,
                                    Description = "Ryuk, a god of death, drops his Death Note into the human world for personal pleasure. In Japan, prodigious high school student Light Yagami stumbles upon it. Inside the notebook, he finds a chilling message: those whose names are written in it shall die. Its nonsensical nature amuses Light; but when he tests its power by writing the name of a criminal in it, they suddenly meet their demise.\n\nRealizing the Death Note's vast potential, Light commences a series of nefarious murders under the pseudonym \"Kira\", vowing to cleanse the world of corrupt individuals and create a perfect society where crime ceases to exist. However, the police quickly catch on, and they enlist the help of L—a mastermind detective—to uncover the culprit.\n\nDeath Note tells the thrilling tale of Light and L as they clash in a great battle-of-minds, one that will determine the future of the world.",
                                    PublishDate = new DateTime(2023, 12, 3, 8, 52, 18, 412, DateTimeKind.Local).AddTicks(8542),
                                    Publishing = "VIZ Media, Shueisha",
                                    TitleRomaji = "Desu Notō",
                                    UpdateDate = new DateTime(2023, 12, 3, 8, 52, 18, 412, DateTimeKind.Local).AddTicks(8546),
                                    Volumes = (short)12,
                                    Votes = 47155
                                });
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.User", b =>
                {
                    b.Navigation("Mangas");
                });
#pragma warning restore 612, 618
        }
    }
}
