// <auto-generated />
using System;
using MangaLibraryAPI.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaLibraryAPI.Migrations
{
    [DbContext(typeof(MangaLibraryContext))]
    [Migration("20231203081522_ManyToMany")]
    partial class ManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MangaLibraryAPI.Entities.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("Enum")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("ID");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Exciting action sequences take priority and significant conflicts between characters are usually resolved with one's physical power.",
                            Enum = (byte)1,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Whether aiming for a specific goal or just struggling to survive, the main character is thrust into unfamiliar situations or lands and continuously faces unexpected dangers.",
                            Enum = (byte)2,
                            Name = "Adventure"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Uplifting the audience with positive emotion takes priority, eliciting laughter, amusement, or general entertainment.",
                            Enum = (byte)3,
                            Name = "Comedy"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Self-explanatory name, stories of this genre can be more relaxing and about trying rich and tasty food or be about dynamic, stressful work in the kitchen.",
                            Enum = (byte)4,
                            Name = "Cooking"
                        },
                        new
                        {
                            ID = 5,
                            Description = "A theme within the Mystery genre, these stories feature either a detective or amateur investigator working to solve a crime or puzzling event.",
                            Enum = (byte)5,
                            Name = "Detective"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Plot-driven stories focused on realistic characters experiencing human struggle.",
                            Enum = (byte)6,
                            Name = "Drama"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Magical powers, unnatural creatures, or other unreal elements which cannot be explained by science are prevalent and normal to the setting they exist in.",
                            Enum = (byte)7,
                            Name = "Fantasy"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Creating—and maintaining—a sense of dread in the audience takes priority, eliciting shock, fear, or disgust through atmosphere and frightening scenarios.",
                            Enum = (byte)8,
                            Name = "Horror"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Stories about life of Japanese idols.",
                            Enum = (byte)9,
                            Name = "Idols"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Protagonist getting transferred into another, unknown world.",
                            Enum = (byte)10,
                            Name = "Isekai"
                        },
                        new
                        {
                            ID = 11,
                            Description = "Piloting giant humanoid robots.",
                            Enum = (byte)11,
                            Name = "Mecha"
                        },
                        new
                        {
                            ID = 12,
                            Description = "Whether its solving a crime or finding an explanation for a puzzling circumstance, the main cast willingly or reluctantly become investigators who must work to answer the who, what, why, and/or how of the current dilemma.",
                            Enum = (byte)12,
                            Name = "Mystery"
                        },
                        new
                        {
                            ID = 13,
                            Description = "Survival after end of the world.",
                            Enum = (byte)13,
                            Name = "Post-apocalypse"
                        },
                        new
                        {
                            ID = 14,
                            Description = "Falling in love and struggling to progress towards—or maintain—a romantic relationship take priority, while other subplots either take backseat or are designed to develop the main love story.",
                            Enum = (byte)14,
                            Name = "Romance"
                        },
                        new
                        {
                            ID = 15,
                            Description = "Imagined technological advancements or natural settings which are currently unreal in the present day but could be invented, caused, or explained by science in the future.",
                            Enum = (byte)15,
                            Name = "Si-Fi"
                        },
                        new
                        {
                            ID = 16,
                            Description = "Slice of Life stories are focused on a seemingly random and mundane period of the main characters' lives.",
                            Enum = (byte)16,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            ID = 17,
                            Description = "Training for and participating in a sport take priority, with the goal of furthering one's athletic abilities—either to win a competition or achieve some social standing.",
                            Enum = (byte)17,
                            Name = "Sports"
                        },
                        new
                        {
                            ID = 18,
                            Description = "Tough life under constant threat of death.",
                            Enum = (byte)18,
                            Name = "Survival"
                        },
                        new
                        {
                            ID = 19,
                            Description = "Heroic fantasy. Subgenre of fantasy characterized by sword-wielding heroes engaged in exciting and violent adventures.",
                            Enum = (byte)19,
                            Name = "SwordAndSorcery"
                        },
                        new
                        {
                            ID = 20,
                            Description = "Characterized and defined by the elicit moods, giving their audiences heightened feelings of suspense, excitement, surprise, anticipation and anxiety.",
                            Enum = (byte)20,
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.Manga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<byte>("Bookmark")
                        .HasColumnType("tinyint");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<short>("ReleaseYear")
                        .HasColumnType("smallint");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TitleEnglish")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitleJapanese")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Mangas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Bookmark = (byte)1,
                            Poster = "https://cdn.myanimelist.net/images/manga/1/157897.jpg",
                            Rating = 9.84f,
                            ReleaseYear = (short)1989,
                            ShortDescription = "Guts, a former mercenary now known as the \"Black Swordsman\", is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything...",
                            Status = (byte)3,
                            TitleEnglish = "Berserk",
                            TitleJapanese = "ベルセルク"
                        },
                        new
                        {
                            ID = 2,
                            Bookmark = (byte)1,
                            Poster = "https://cdn.myanimelist.net/images/manga/3/265854.jpg",
                            Rating = 9.36f,
                            ReleaseYear = (short)2005,
                            ShortDescription = "\"Akumajō Dracula: Yami no Juin\" had in Japan its own comic series that lasted all of two volumes. The comic series of the same name was created in 2005 by company Mediafactory, and it follows events that overlap with bonus-material comic...",
                            Status = (byte)4,
                            TitleEnglish = "Castlevania: Curse of Darkness",
                            TitleJapanese = "悪魔城ドラキュラ 闇の呪印"
                        },
                        new
                        {
                            ID = 3,
                            Bookmark = (byte)1,
                            Poster = "https://cover.imglib.info/uploads/cover/desu-noto/cover/5UcB013CNhll_250x350.jpg",
                            Rating = 9.6f,
                            ReleaseYear = (short)2003,
                            ShortDescription = "Ryuk, a god of death, drops his Death Note into the human world for personal pleasure. In Japan, prodigious high school student Light Yagami stumbles upon it. Inside the notebook, he finds a chilling message: those whose names are written in it shall die.",
                            Status = (byte)4,
                            TitleEnglish = "Death Note",
                            TitleJapanese = "デスノート"
                        });
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.MtMRO.MangaGenre", b =>
                {
                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<int>("MangaID")
                        .HasColumnType("int");

                    b.HasKey("GenreID", "MangaID");

                    b.HasIndex("MangaID");

                    b.ToTable("MangaGenre");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 8,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 2,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 7,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 19,
                            MangaID = 1
                        },
                        new
                        {
                            GenreID = 1,
                            MangaID = 2
                        },
                        new
                        {
                            GenreID = 6,
                            MangaID = 2
                        },
                        new
                        {
                            GenreID = 7,
                            MangaID = 2
                        },
                        new
                        {
                            GenreID = 1,
                            MangaID = 3
                        },
                        new
                        {
                            GenreID = 6,
                            MangaID = 3
                        },
                        new
                        {
                            GenreID = 5,
                            MangaID = 3
                        },
                        new
                        {
                            GenreID = 20,
                            MangaID = 3
                        });
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.MtMRO.MangaTag", b =>
                {
                    b.Property<int>("MangaID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("MangaID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("MangaTag");

                    b.HasData(
                        new
                        {
                            MangaID = 1,
                            TagID = 9
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 20
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 7
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 51
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 31
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 40
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 30
                        },
                        new
                        {
                            MangaID = 1,
                            TagID = 48
                        },
                        new
                        {
                            MangaID = 2,
                            TagID = 35
                        },
                        new
                        {
                            MangaID = 2,
                            TagID = 50
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 40
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 35
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 48
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 19
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 7
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 30
                        },
                        new
                        {
                            MangaID = 3,
                            TagID = 6
                        });
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<byte>("Tags")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Attempt to purify, mature, and perfect certain materials, like the transmutation of \"base metals\" (e.g., lead) into \"noble metals\" (particularly gold).",
                            Name = "Alchemy",
                            Tags = (byte)1
                        },
                        new
                        {
                            ID = 2,
                            Description = "Whole or partial loss of memory.",
                            Name = "Amnesia",
                            Tags = (byte)2
                        },
                        new
                        {
                            ID = 3,
                            Description = "Usually shaped like humans of extraordinary beauty, often identified with bird wings, halos, and divine light.",
                            Name = "Angels",
                            Tags = (byte)3
                        },
                        new
                        {
                            ID = 4,
                            Description = "Anthropomorphs: non-human creatures attributed with human traits and emotions.",
                            Name = "Anthropomorphic",
                            Tags = (byte)4
                        },
                        new
                        {
                            ID = 5,
                            Description = "Half-humans & half-animals.",
                            Name = "DemiHuman",
                            Tags = (byte)5
                        },
                        new
                        {
                            ID = 6,
                            Description = "Coercion using the threat of revealing compromising information about a person to the public.",
                            Name = "Blackmail",
                            Tags = (byte)6
                        },
                        new
                        {
                            ID = 7,
                            Description = "Cold and unforgiving.",
                            Name = "CruelWorld",
                            Tags = (byte)7
                        },
                        new
                        {
                            ID = 8,
                            Description = "Dystopian si-fi future that tends to focus on a combination of lowlife and high tech.",
                            Name = "Cyberpunk",
                            Tags = (byte)8
                        },
                        new
                        {
                            ID = 9,
                            Description = "Evil beings, minions of the devil, often humanoid, often depicted with horns, bat-like wings, and pointy spear-like tail.",
                            Name = "Demons",
                            Tags = (byte)9
                        },
                        new
                        {
                            ID = 10,
                            Description = "Large magical legendary creatures.",
                            Name = "Dragons",
                            Tags = (byte)10
                        },
                        new
                        {
                            ID = 11,
                            Description = "Not the smartest.",
                            Name = "DumbProtagonist",
                            Tags = (byte)11
                        },
                        new
                        {
                            ID = 12,
                            Description = "Monster filled caves/underground places.",
                            Name = "Dungeon",
                            Tags = (byte)12
                        },
                        new
                        {
                            ID = 13,
                            Description = "Distinctive sign of elves are their pointy ears. Commonly shown as creatures with great beauty.",
                            Name = "Elves",
                            Tags = (byte)13
                        },
                        new
                        {
                            ID = 14,
                            Description = "Political unit made up of several territories and peoples, usually created by conquest and controlled by the center, the metropole of the empire.",
                            Name = "Empires",
                            Tags = (byte)14
                        },
                        new
                        {
                            ID = 15,
                            Description = "Female main character.",
                            Name = "FemaleProtagonist",
                            Tags = (byte)15
                        },
                        new
                        {
                            ID = 16,
                            Description = "World in the far future.",
                            Name = "Future",
                            Tags = (byte)16
                        },
                        new
                        {
                            ID = 17,
                            Description = "Wagering of money with intent of winning more money, where instances of strategy are discounted.",
                            Name = "Gambling",
                            Tags = (byte)17
                        },
                        new
                        {
                            ID = 18,
                            Description = "Soul or spirit of a dead person or another creature that is able to appear to the living.",
                            Name = "Ghosts",
                            Tags = (byte)18
                        },
                        new
                        {
                            ID = 19,
                            Description = "All-mighty supernatural creature.",
                            Name = "Gods",
                            Tags = (byte)19
                        },
                        new
                        {
                            ID = 20,
                            Description = "Blood and violence.",
                            Name = "Gore",
                            Tags = (byte)20
                        },
                        new
                        {
                            ID = 21,
                            Description = "Japanese subculture, nonconformist or rebelling against Japanese social and aesthetic standards.",
                            Name = "Gyaru",
                            Tags = (byte)21
                        },
                        new
                        {
                            ID = 22,
                            Description = "Bunch of women constantly surrounding the protagonist.",
                            Name = "Harem",
                            Tags = (byte)22
                        },
                        new
                        {
                            ID = 23,
                            Description = "Total withdrawal from society and seeking extreme degrees of social isolation and confinement.",
                            Name = "Hikikomori",
                            Tags = (byte)23
                        },
                        new
                        {
                            ID = 24,
                            Description = "Honorable, noble warrior fully clad in plate armor. Usually armed with sword and shield.",
                            Name = "Knights",
                            Tags = (byte)24
                        },
                        new
                        {
                            ID = 25,
                            Description = "Stands for \"lesbian, gay, bisexual, transgender and queer\"",
                            Name = "LGBTQ",
                            Tags = (byte)25
                        },
                        new
                        {
                            ID = 26,
                            Description = "Italian criminal organization.",
                            Name = "Mafia",
                            Tags = (byte)26
                        },
                        new
                        {
                            ID = 27,
                            Description = "People with ability to use magic.",
                            Name = "Mages",
                            Tags = (byte)27
                        },
                        new
                        {
                            ID = 28,
                            Description = "Place where students learn, perfect, or extend their magical powers and knowledge.",
                            Name = "MagicAcademy",
                            Tags = (byte)28
                        },
                        new
                        {
                            ID = 29,
                            Description = "Female domestic worker. In manga depicted in style of Victorian era French maids.",
                            Name = "Maids",
                            Tags = (byte)29
                        },
                        new
                        {
                            ID = 30,
                            Description = "Male main character.",
                            Name = "MaleProtagonist",
                            Tags = (byte)30
                        },
                        new
                        {
                            ID = 31,
                            Description = "Stories in style of European mediæval period.",
                            Name = "Medieval",
                            Tags = (byte)31
                        },
                        new
                        {
                            ID = 32,
                            Description = "Life as a soldier.",
                            Name = "Military",
                            Tags = (byte)32
                        },
                        new
                        {
                            ID = 33,
                            Description = "Half-girl & half-monster.",
                            Name = "Monstergirls",
                            Tags = (byte)33
                        },
                        new
                        {
                            ID = 34,
                            Description = "Often about life in musical band.",
                            Name = "Music",
                            Tags = (byte)34
                        },
                        new
                        {
                            ID = 35,
                            Description = "Mythical creatures, monsters.",
                            Name = "Mythology",
                            Tags = (byte)35
                        },
                        new
                        {
                            ID = 36,
                            Description = "Japanese assassin.",
                            Name = "Ninja",
                            Tags = (byte)36
                        },
                        new
                        {
                            ID = 37,
                            Description = "Parody of common storytelling tropes.",
                            Name = "Parody",
                            Tags = (byte)37
                        },
                        new
                        {
                            ID = 38,
                            Description = "Sea bandits.",
                            Name = "Pirates",
                            Tags = (byte)38
                        },
                        new
                        {
                            ID = 39,
                            Description = "Power relations among individuals, such as the distribution of resources or status. Sometimes just depiction of political figures.",
                            Name = "Politics",
                            Tags = (byte)39
                        },
                        new
                        {
                            ID = 40,
                            Description = "Mind games, mental anguish, etc.",
                            Name = "Psychological",
                            Tags = (byte)40
                        },
                        new
                        {
                            ID = 41,
                            Description = "Journey toward a specific mission or a goal.",
                            Name = "Quests",
                            Tags = (byte)41
                        },
                        new
                        {
                            ID = 42,
                            Description = "Rebirth in another world after death.",
                            Name = "Reincarnation",
                            Tags = (byte)42
                        },
                        new
                        {
                            ID = 43,
                            Description = "Machine programmable by a computer—capable of carrying out a complex series of actions automatically.",
                            Name = "Robots",
                            Tags = (byte)43
                        },
                        new
                        {
                            ID = 44,
                            Description = "Military nobility, officer caste of medieval Japan, wearing traditional clothes and wielding katanas.",
                            Name = "Samurais",
                            Tags = (byte)44
                        },
                        new
                        {
                            ID = 45,
                            Description = "People being owned and treated like property.",
                            Name = "Slaves",
                            Tags = (byte)45
                        },
                        new
                        {
                            ID = 46,
                            Description = "Rare case.",
                            Name = "SmartProtagonist",
                            Tags = (byte)46
                        },
                        new
                        {
                            ID = 47,
                            Description = "Retrofuturistic aesthetics inspired by 19th-century industrial steam-powered machinery.",
                            Name = "Steampunk",
                            Tags = (byte)47
                        },
                        new
                        {
                            ID = 48,
                            Description = "Primarily taking place on Earth, supernatural stories incorporate elements or attributes that are unnatural and unexplainable by science.",
                            Name = "Supernatural",
                            Tags = (byte)48
                        },
                        new
                        {
                            ID = 49,
                            Description = "Living dead, like zombies or skeletons.",
                            Name = "Undead",
                            Tags = (byte)49
                        },
                        new
                        {
                            ID = 50,
                            Description = "Blood-suckers.",
                            Name = "Vampires",
                            Tags = (byte)50
                        },
                        new
                        {
                            ID = 51,
                            Description = "Story driven around protagonist's desire for retribution.",
                            Name = "Vengeance",
                            Tags = (byte)51
                        },
                        new
                        {
                            ID = 52,
                            Description = "Electronic games.",
                            Name = "Videogames",
                            Tags = (byte)52
                        },
                        new
                        {
                            ID = 53,
                            Description = "Reality but virtual.",
                            Name = "VirtualReality",
                            Tags = (byte)53
                        },
                        new
                        {
                            ID = 54,
                            Description = "Practitioner of witchcraft: magic used to inflict harm or misfortune on others.",
                            Name = "Witch",
                            Tags = (byte)54
                        },
                        new
                        {
                            ID = 55,
                            Description = "Japanese mafioso.",
                            Name = "Yakudza",
                            Tags = (byte)55
                        },
                        new
                        {
                            ID = 56,
                            Description = "Initially loving and caring until their romantic love, admiration and devotion becomes feisty and mentally destructive in nature through either overprotectiveness, violence, brutality or all three combined.",
                            Name = "Yandere",
                            Tags = (byte)56
                        },
                        new
                        {
                            ID = 57,
                            Description = "Green, undead brain-lover.",
                            Name = "Zombie",
                            Tags = (byte)57
                        });
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "obichnichelovek@vk.com",
                            Name = "Admin",
                            Password = "SuperSecretPassword",
                            Role = (byte)2
                        });
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.Manga", b =>
                {
                    b.HasOne("MangaLibraryAPI.Entities.User", null)
                        .WithMany("Mangas")
                        .HasForeignKey("UserID");

                    b.OwnsOne("MangaLibraryAPI.Entities.MangaDetails", "Details", b1 =>
                        {
                            b1.Property<int>("MangaID")
                                .HasColumnType("int");

                            b1.Property<string>("Artist")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Author")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<short>("Chapters")
                                .HasColumnType("smallint");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<DateTime>("PublishDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Publishing")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TitleRomaji")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<DateTime>("UpdateDate")
                                .HasColumnType("datetime2");

                            b1.Property<short>("Volumes")
                                .HasColumnType("smallint");

                            b1.Property<int>("Votes")
                                .HasColumnType("int");

                            b1.HasKey("MangaID");

                            b1.ToTable("MangaDetails");

                            b1.WithOwner("Manga")
                                .HasForeignKey("MangaID");

                            b1.Navigation("Manga");

                            b1.HasData(
                                new
                                {
                                    MangaID = 1,
                                    Artist = "Kentaro Miura",
                                    Author = "Kentaro Miura",
                                    Chapters = (short)376,
                                    Description = "Guts, a former mercenary now known as the \"Black Swordsman\", is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings.\n\nSetting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him—and his loved one—of their humanity.",
                                    PublishDate = new DateTime(2023, 12, 3, 12, 15, 20, 109, DateTimeKind.Local).AddTicks(9462),
                                    Publishing = "Hakusensha, Dark Horse Comics, XL Media",
                                    TitleRomaji = "Beruseruku",
                                    UpdateDate = new DateTime(2023, 12, 3, 12, 15, 20, 109, DateTimeKind.Local).AddTicks(9488),
                                    Volumes = (short)41,
                                    Votes = 12646
                                },
                                new
                                {
                                    MangaID = 2,
                                    Artist = "SASAKURA Kou",
                                    Author = "SASAKURA Kou",
                                    Chapters = (short)4,
                                    Description = "\"Akumajō Dracula: Yami no Juin\" had in Japan its own comic series that lasted all of two volumes. The comic series of the same name was created in 2005 by company Mediafactory, and it follows events that overlap with bonus-material comic Prelude of Revenge, whose story was conceived by Ayami Kojima; the series is, according to her, a true extension of the of both Prelude and therein the game's actual story. Adding to its authenticity is the knowledge that Koji Igarashi completely supervised its creation.",
                                    PublishDate = new DateTime(2023, 12, 3, 12, 15, 20, 109, DateTimeKind.Local).AddTicks(9502),
                                    Publishing = "Media Factory",
                                    TitleRomaji = "Akumajō Dracula: Yami no Juin",
                                    UpdateDate = new DateTime(2023, 12, 3, 12, 15, 20, 109, DateTimeKind.Local).AddTicks(9510),
                                    Volumes = (short)2,
                                    Votes = 42
                                },
                                new
                                {
                                    MangaID = 3,
                                    Artist = "Takeshi Obata",
                                    Author = "Tsugumi Ohba",
                                    Chapters = (short)117,
                                    Description = "Ryuk, a god of death, drops his Death Note into the human world for personal pleasure. In Japan, prodigious high school student Light Yagami stumbles upon it. Inside the notebook, he finds a chilling message: those whose names are written in it shall die. Its nonsensical nature amuses Light; but when he tests its power by writing the name of a criminal in it, they suddenly meet their demise.\n\nRealizing the Death Note's vast potential, Light commences a series of nefarious murders under the pseudonym \"Kira\", vowing to cleanse the world of corrupt individuals and create a perfect society where crime ceases to exist. However, the police quickly catch on, and they enlist the help of L—a mastermind detective—to uncover the culprit.\n\nDeath Note tells the thrilling tale of Light and L as they clash in a great battle-of-minds, one that will determine the future of the world.",
                                    PublishDate = new DateTime(2023, 12, 3, 12, 15, 20, 109, DateTimeKind.Local).AddTicks(9519),
                                    Publishing = "VIZ Media, Shueisha",
                                    TitleRomaji = "Desu Notō",
                                    UpdateDate = new DateTime(2023, 12, 3, 12, 15, 20, 109, DateTimeKind.Local).AddTicks(9528),
                                    Volumes = (short)12,
                                    Votes = 47155
                                });
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.MtMRO.MangaGenre", b =>
                {
                    b.HasOne("MangaLibraryAPI.Entities.Genre", "Genre")
                        .WithMany("MangaGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaLibraryAPI.Entities.Manga", "Manga")
                        .WithMany("MangaGenres")
                        .HasForeignKey("MangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.MtMRO.MangaTag", b =>
                {
                    b.HasOne("MangaLibraryAPI.Entities.Manga", "Manga")
                        .WithMany("MangaTags")
                        .HasForeignKey("MangaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaLibraryAPI.Entities.Tag", "Tag")
                        .WithMany("MangaTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.Genre", b =>
                {
                    b.Navigation("MangaGenres");
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.Manga", b =>
                {
                    b.Navigation("MangaGenres");

                    b.Navigation("MangaTags");
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.Tag", b =>
                {
                    b.Navigation("MangaTags");
                });

            modelBuilder.Entity("MangaLibraryAPI.Entities.User", b =>
                {
                    b.Navigation("Mangas");
                });
#pragma warning restore 612, 618
        }
    }
}
